sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_a5dfb9c642ba_key -iv $encrypted_a5dfb9c642ba_iv
  -in key.json.enc -out key.json -d
- export CLOUDSDK_CORE_DISABLE_PROMPTS=1
- curl https://sdk.cloud.google.com | bash
- docker login -u _json_key --password-stdin https://eu.gcr.io < key.json
script:
- docker build -t eu.gcr.io/motorik-208520/lastfm-dump:latest .
deploy:
- provider: script
  script: docker push eu.gcr.io/motorik-208520/lastfm-dump:latest
  on:
    branch: master
