sudo: required
services:
- docker
before_install:
- CLOUDSDK_CORE_DISABLE_PROMPTS=1 curl https://sdk.cloud.google.com | bash
- openssl aes-256-cbc -K $encrypted_a5dfb9c642ba_key -iv $encrypted_a5dfb9c642ba_iv -in motorik-208520-e2bc6054a6fb.json.enc -out motorik-208520-e2bc6054a6fb.json -d
- docker login -u _json_key --password-stdin https://eu.gcr.io < motorik-208520-e2bc6054a6fb.json
script:
- docker build -t eu.gcr.io/motorik-208520/lastfm-dump:latest .
deploy:
- provider: script
  script: docker push eu.gcr.io/motorik-208520/lastfm-dump:latest
  on:
    branch: master

