resolver: lts-11.15
packages:
- .
docker:
  enable: true
image:
  containers:
    - base: "haskell:8"
      name: "jliuhtonen/lastfm-dump"
      executables:
        - "lastfm-dump"
      entrypoints:
        - "lastfm-dump"
